import type { CoreBackendApp } from "./entry/app.ts";
import type { CoreBackendArtifact } from "./entry/artifact/types.ts";
import type { CoreBackendClosure } from "./closure/types.ts";
import type { CoreBackendControlFlow } from "./control_flow/types.ts";
import type { CoreBackendExprEmit } from "./emit/expr.ts";
import type { CoreBackendExprType } from "./analysis/expr_type.ts";
import type { CoreBackendIndex } from "./entry/index.ts";
import type { CoreBackendLocalCollect } from "./entry/local_collect/types.ts";
import type { CoreBackendLocalFacts } from "./analysis/local_facts.ts";
import type { CoreBackendRec } from "./runtime/rec/types.ts";
import type { CoreBackendStaticCall } from "./values/static_call/types.ts";
import type { CoreBackendStaticValue } from "./values/static_value/types.ts";
import type { CoreBackendStmtEmit } from "./emit/stmt.ts";
import type { CoreBackendStruct } from "./values/struct/types.ts";
import type { CoreBackendText } from "./text/types.ts";
import type { CoreBackendTypeCheck } from "./analysis/type_check.ts";
import type { CoreBackendUnion } from "./union/types.ts";

export type CoreBackendGraphDeps = {
  app: () => CoreBackendApp;
  artifact: () => CoreBackendArtifact;
  closure: () => CoreBackendClosure;
  control_flow: () => CoreBackendControlFlow;
  expr_emit: () => CoreBackendExprEmit;
  expr_type: () => CoreBackendExprType;
  index: () => CoreBackendIndex;
  local_collect: () => CoreBackendLocalCollect;
  local_facts: () => CoreBackendLocalFacts;
  rec: () => CoreBackendRec;
  static_call: () => CoreBackendStaticCall;
  static_value: () => CoreBackendStaticValue;
  stmt_emit: () => CoreBackendStmtEmit;
  struct: () => CoreBackendStruct;
  text: () => CoreBackendText;
  type_check: () => CoreBackendTypeCheck;
  union: () => CoreBackendUnion;
};
