// Generated by @mewhhaha/baba. Do not edit by hand.
#include "tree_sitter/parser.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define BABA_TOKEN_COUNT 3
#define BABA_GUARD_STATE_COUNT 8
#define BABA_WORD_COUNT 28
#define BABA_WORD_STORAGE_COUNT 28

enum TokenType {
  BABA_EXTERNAL_TOKEN_0,
  BABA_EXTERNAL_TOKEN_1,
  BABA_EXTERNAL_TOKEN_2,
  BABA_ERROR_SENTINEL,
};

enum GuardStatus {
  BABA_GUARD_PENDING,
  BABA_GUARD_PASSES,
  BABA_GUARD_FAILS,
};

struct BabaTransition {
  int32_t start;
  int32_t end;
  int32_t target;
};

static const int32_t BABA_TOKEN_STARTS[] = { 0, 3, 6 };
static const int32_t BABA_TOKEN_ACCEPTS[] = { 0, 1, 1, 0, 1, 1, 0, 1, 1 };
static const int32_t BABA_TOKEN_TRANSITION_ROWS[] = { 0, 2, 4, 6, 8, 10, 12, 14, 16, 18 };
static const struct BabaTransition BABA_TOKEN_TRANSITIONS[] = { { 9, 9, 1 }, { 32, 32, 1 }, { 9, 9, 2 }, { 32, 32, 2 }, { 9, 9, 2 }, { 32, 32, 2 }, { 9, 9, 4 }, { 32, 32, 4 }, { 9, 9, 5 }, { 32, 32, 5 }, { 9, 9, 5 }, { 32, 32, 5 }, { 9, 9, 7 }, { 32, 32, 7 }, { 9, 9, 8 }, { 32, 32, 8 }, { 9, 9, 8 }, { 32, 32, 8 } };
static const int32_t BABA_GUARD_ACCEPTS[] = { 0, 1, 0, 1, 0, 1, 1, 1 };
static const int32_t BABA_GUARD_TRANSITION_ROWS[] = { 0, 6, 6, 12, 12, 19, 19, 19, 19 };
static const struct BabaTransition BABA_GUARD_TRANSITIONS[] = { { 33, 35, 1 }, { 38, 40, 1 }, { 48, 57, 1 }, { 64, 91, 1 }, { 95, 95, 1 }, { 97, 123, 1 }, { 33, 35, 3 }, { 38, 40, 3 }, { 48, 57, 3 }, { 64, 91, 3 }, { 95, 95, 3 }, { 97, 122, 3 }, { 35, 35, 5 }, { 38, 38, 5 }, { 40, 40, 6 }, { 65, 90, 5 }, { 91, 91, 7 }, { 95, 95, 5 }, { 97, 122, 5 } };
static const int32_t BABA_POSITIVE_STARTS[] = { 0, 2, 4 };
static const int32_t BABA_POSITIVE_EOF[] = { 0, 0, 0 };
static const int32_t BABA_NEGATIVE_STARTS[] = { -1, -1, -1 };
static const int32_t BABA_TOKEN_WORD_ROWS[] = { 0, 12, 24, 28 };
static const int32_t BABA_WORD_ROWS[] = { 0, 2, 4, 6, 10, 13, 15, 17, 19, 21, 25, 30, 34, 36, 38, 40, 44, 47, 49, 51, 53, 55, 59, 64, 68, 70, 74, 77, 81 };
static const int32_t BABA_WORD_CODE_POINTS[] = { 97, 115, 98, 121, 100, 111, 101, 108, 115, 101, 101, 110, 100, 105, 102, 105, 110, 105, 115, 111, 102, 116, 104, 101, 110, 119, 104, 101, 114, 101, 119, 105, 116, 104, 97, 115, 98, 121, 100, 111, 101, 108, 115, 101, 101, 110, 100, 105, 102, 105, 110, 105, 115, 111, 102, 116, 104, 101, 110, 119, 104, 101, 114, 101, 119, 105, 116, 104, 100, 111, 101, 108, 115, 101, 101, 110, 100, 116, 104, 101, 110 };
static const int32_t BABA_TOKEN_PRECEDENCE[] = { 0, 1, 2 };

static int32_t baba_transition(
  const int32_t *rows,
  const struct BabaTransition *transitions,
  int32_t state,
  int32_t code_point
) {
  int32_t low = rows[state];
  int32_t high = rows[state + 1];
  while (low < high) {
    int32_t middle = low + (high - low) / 2;
    const struct BabaTransition *transition = &transitions[middle];
    if (code_point < transition->start) {
      high = middle;
      continue;
    }
    if (code_point > transition->end) {
      low = middle + 1;
      continue;
    }
    return transition->target;
  }
  return -1;
}

static bool baba_word_code_point(int32_t code_point) {
  if (code_point >= 'A' && code_point <= 'Z') {
    return true;
  }
  if (code_point >= 'a' && code_point <= 'z') {
    return true;
  }
  if (code_point >= '0' && code_point <= '9') {
    return true;
  }
  return code_point == '_';
}

static bool baba_scan_guards(
  TSLexer *lexer,
  const bool *valid_symbols,
  const int32_t *token_states
) {
  bool candidates[BABA_TOKEN_COUNT] = { false };
  int32_t positive_states[BABA_TOKEN_COUNT];
  int32_t negative_states[BABA_TOKEN_COUNT];
  enum GuardStatus positive[BABA_TOKEN_COUNT];
  enum GuardStatus negative[BABA_TOKEN_COUNT];
  enum GuardStatus excluded_words[BABA_TOKEN_COUNT];
  bool word_candidates[BABA_WORD_STORAGE_COUNT] = { false };
  int32_t word_positions[BABA_WORD_STORAGE_COUNT] = { 0 };

  for (int32_t token = 0; token < BABA_TOKEN_COUNT; token++) {
    int32_t state = token_states[token];
    if (state < 0 || BABA_TOKEN_ACCEPTS[state] == 0) {
      continue;
    }
    if (!valid_symbols[token]) {
      continue;
    }
    candidates[token] = true;
    positive_states[token] = BABA_POSITIVE_STARTS[token];
    negative_states[token] = BABA_NEGATIVE_STARTS[token];
    positive[token] = BABA_GUARD_PENDING;
    if (negative_states[token] < 0) {
      negative[token] = BABA_GUARD_PASSES;
    } else {
      negative[token] = BABA_GUARD_PENDING;
    }
    int32_t word_start = BABA_TOKEN_WORD_ROWS[token];
    int32_t word_end = BABA_TOKEN_WORD_ROWS[token + 1];
    if (word_start == word_end) {
      excluded_words[token] = BABA_GUARD_PASSES;
    } else {
      excluded_words[token] = BABA_GUARD_PENDING;
      for (int32_t word = word_start; word < word_end; word++) {
        word_candidates[word] = true;
      }
    }
  }

  while (true) {
    bool at_eof = lexer->eof(lexer);
    for (int32_t token = 0; token < BABA_TOKEN_COUNT; token++) {
      if (!candidates[token]) {
        continue;
      }
      if (positive[token] == BABA_GUARD_PENDING) {
        int32_t state = positive_states[token];
        if (state >= 0 && BABA_GUARD_ACCEPTS[state] != 0) {
          positive[token] = BABA_GUARD_PASSES;
        } else if (at_eof && BABA_POSITIVE_EOF[token] != 0) {
          positive[token] = BABA_GUARD_PASSES;
        } else if (at_eof) {
          positive[token] = BABA_GUARD_FAILS;
        }
      }
      if (negative[token] == BABA_GUARD_PENDING) {
        int32_t state = negative_states[token];
        if (BABA_GUARD_ACCEPTS[state] != 0) {
          negative[token] = BABA_GUARD_FAILS;
        } else if (at_eof) {
          negative[token] = BABA_GUARD_PASSES;
        }
      }
      if (excluded_words[token] == BABA_GUARD_PENDING) {
        bool any_word_candidate = false;
        int32_t word_start = BABA_TOKEN_WORD_ROWS[token];
        int32_t word_end = BABA_TOKEN_WORD_ROWS[token + 1];
        for (int32_t word = word_start; word < word_end; word++) {
          if (!word_candidates[word]) {
            continue;
          }
          int32_t position = word_positions[word];
          int32_t length = BABA_WORD_ROWS[word + 1] - BABA_WORD_ROWS[word];
          if (position == length) {
            word_candidates[word] = false;
            if (at_eof || !baba_word_code_point(lexer->lookahead)) {
              excluded_words[token] = BABA_GUARD_FAILS;
              break;
            }
            continue;
          }
          if (at_eof) {
            word_candidates[word] = false;
            continue;
          }
          int32_t expected = BABA_WORD_CODE_POINTS[
            BABA_WORD_ROWS[word] + position
          ];
          if (lexer->lookahead != expected) {
            word_candidates[word] = false;
            continue;
          }
          any_word_candidate = true;
        }
        if (
          excluded_words[token] == BABA_GUARD_PENDING &&
          !any_word_candidate
        ) {
          excluded_words[token] = BABA_GUARD_PASSES;
        }
      }
      if (
        positive[token] == BABA_GUARD_FAILS ||
        negative[token] == BABA_GUARD_FAILS ||
        excluded_words[token] == BABA_GUARD_FAILS
      ) {
        candidates[token] = false;
      }
    }

    bool has_candidate = false;
    for (int32_t index = 0; index < BABA_TOKEN_COUNT; index++) {
      int32_t token = BABA_TOKEN_PRECEDENCE[index];
      if (!candidates[token]) {
        continue;
      }
      has_candidate = true;
      if (
        positive[token] == BABA_GUARD_PASSES &&
        negative[token] == BABA_GUARD_PASSES &&
        excluded_words[token] == BABA_GUARD_PASSES
      ) {
        lexer->result_symbol = (TSSymbol)token;
        return true;
      }
      break;
    }
    if (!has_candidate || at_eof) {
      return false;
    }

    int32_t code_point = lexer->lookahead;
    for (int32_t token = 0; token < BABA_TOKEN_COUNT; token++) {
      if (!candidates[token]) {
        continue;
      }
      if (positive[token] == BABA_GUARD_PENDING) {
        int32_t state = positive_states[token];
        if (state < 0) {
          positive[token] = BABA_GUARD_FAILS;
        } else {
          int32_t target = baba_transition(
            BABA_GUARD_TRANSITION_ROWS,
            BABA_GUARD_TRANSITIONS,
            state,
            code_point
          );
          if (target < 0) {
            positive[token] = BABA_GUARD_FAILS;
          } else {
            positive_states[token] = target;
          }
        }
      }
      if (negative[token] == BABA_GUARD_PENDING) {
        int32_t target = baba_transition(
          BABA_GUARD_TRANSITION_ROWS,
          BABA_GUARD_TRANSITIONS,
          negative_states[token],
          code_point
        );
        if (target < 0) {
          negative[token] = BABA_GUARD_PASSES;
        } else {
          negative_states[token] = target;
        }
      }
      if (excluded_words[token] == BABA_GUARD_PENDING) {
        int32_t word_start = BABA_TOKEN_WORD_ROWS[token];
        int32_t word_end = BABA_TOKEN_WORD_ROWS[token + 1];
        for (int32_t word = word_start; word < word_end; word++) {
          if (word_candidates[word]) {
            word_positions[word] += 1;
          }
        }
      }
    }
    lexer->advance(lexer, false);
  }
}

void *tree_sitter_duck_external_scanner_create(void) {
  return NULL;
}

void tree_sitter_duck_external_scanner_destroy(void *payload) {
  (void)payload;
}

unsigned tree_sitter_duck_external_scanner_serialize(void *payload, char *buffer) {
  (void)payload;
  (void)buffer;
  return 0;
}

void tree_sitter_duck_external_scanner_deserialize(
  void *payload,
  const char *buffer,
  unsigned length
) {
  (void)payload;
  (void)buffer;
  (void)length;
}

bool tree_sitter_duck_external_scanner_scan(
  void *payload,
  TSLexer *lexer,
  const bool *valid_symbols
) {
  (void)payload;
  if (valid_symbols[BABA_ERROR_SENTINEL]) {
    return false;
  }

  int32_t states[BABA_TOKEN_COUNT];
  int32_t targets[BABA_TOKEN_COUNT];
  for (int32_t token = 0; token < BABA_TOKEN_COUNT; token++) {
    if (valid_symbols[token]) {
      states[token] = BABA_TOKEN_STARTS[token];
    } else {
      states[token] = -1;
    }
  }

  while (!lexer->eof(lexer)) {
    bool any_transition = false;
    for (int32_t token = 0; token < BABA_TOKEN_COUNT; token++) {
      if (states[token] < 0) {
        targets[token] = -1;
        continue;
      }
      targets[token] = baba_transition(
        BABA_TOKEN_TRANSITION_ROWS,
        BABA_TOKEN_TRANSITIONS,
        states[token],
        lexer->lookahead
      );
      if (targets[token] >= 0) {
        any_transition = true;
      }
    }
    if (!any_transition) {
      break;
    }
    lexer->advance(lexer, false);
    for (int32_t token = 0; token < BABA_TOKEN_COUNT; token++) {
      states[token] = targets[token];
    }
  }

  bool any_candidate = false;
  for (int32_t token = 0; token < BABA_TOKEN_COUNT; token++) {
    int32_t state = states[token];
    if (state >= 0 && BABA_TOKEN_ACCEPTS[state] != 0) {
      any_candidate = true;
      break;
    }
  }
  if (!any_candidate) {
    return false;
  }
  lexer->mark_end(lexer);
  return baba_scan_guards(lexer, valid_symbols, states);
}
